### ISSUE TITLE
German language Chatbot

### ISSUE THREAD

**Issue by VikasRajashekar** [HLTCHKUST/Xpersona#2]
Can this work on German data? 
What model changes are required to bring in German pre-trained models?

**Comment by zlinao** [comment]
Yes, you can extend this work to German Chatbot.

If you want a German monolingual chatbot, you can add your data in dataset folder, and convert the dataset format by following: https://github.com/HLTCHKUST/Xpersona/blob/master/multilingual/combine_dataset.py

you can add the {"De": "bert-base-german-cased"} to add the German BERT in 
https://github.com/HLTCHKUST/Xpersona/blob/45750ab473d325a2428698df98fbca025875ef8d/multilingual/train_decoder_only.py#L29

you can check https://github.com/HLTCHKUST/Xpersona/blob/45750ab473d325a2428698df98fbca025875ef8d/multilingual/run.sh#L10 to know how to train a monolingual model

**Comment by VikasRajashekar** [comment]
@zlinao Thanks for the reply. So I need to first translate the persona dataset to German and then convert it to required format using combine_dataset.py.

Next LANG_2_MODEL need to change to add German Bert .

and then I train the network using run.sh. Is this the procedure?

**Comment by zlinao** [comment]
yes, you might need to modify few lines of code to extend the possible language like https://github.com/HLTCHKUST/Xpersona/blob/45750ab473d325a2428698df98fbca025875ef8d/multilingual/utils.py#L83
